name: Run Qual Tests

on:
  repository_dispatch:
    types: [run-qual-tests]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    if: github.event.client_payload.feature_tag == 'feature:my-app'
    steps:
      - name: Checkout qual repo
        uses: actions/checkout@v4

      - name: Checkout my-app PR branch
        uses: actions/checkout@v4
        with:
          repository: modihimanshu-36/my-app
          ref: ${{ github.event.client_payload.pr_branch }}
          path: my-app
        #   token: ${{ secrets.MY_APP_TOKEN }}            # <-- Only needed if my-app is private

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (qual)
        run: npm ci

      - name: Run qual tests for my-app
        run: |
          # Replace with your actual test command if needed
          npm test